name: Deploy Flask app to GCP

on:
  push:
    branches: [master]

jobs:
  # make_settings_run_test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # python 설치
  #     - uses: actions/checkout@v2
  #     - name: Set up python
  #       uses: actions/setup-python@v1
  #       with:
  #         python-version: 3.9
      
  #     # python 모듈 설치
  #     - name: Install python Dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
        
  #     - name: echo workspace
  #       run: echo $GITHUB_WORKSPACE
  #       shell: bash

  #     # python app 실행 테스트
  #     - name: run test
  #       run: coverage run -m unittest app.py

  #     - name: test report
  #       run: coverage report

  # gcp 배포
  build_and_deploy:
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}

    needs: [make_settings_run_test]
    runs-on: ubuntu-latest

    steps:
      - name: GCP login
        uses: google-github-actions/auth@v1
        with:
          # service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          credentials_json: ${{ secrets.GCP_SA_KEYS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: |
          gcloud info
          gcloud projects list
          gcloud compute instances list
        
      - name: Upload Folder
        run: |
          gcloud compute scp static/* templates/* models/* app.py model_utils.py utils.py \
          ${{ secrets.SSH_USER }}@dh-server:/home/src/ML_news_topic_classification --zone=${{ env.REGION }}